/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderVue: typeof import('./components/HeaderVue.vue')['default']
    MainVue: typeof import('./components/MainVue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInputVue: typeof import('./components/SearchInputVue.vue')['default']
    StarredReposVue: typeof import('./components/StarredReposVue.vue')['default']
  }
}
